locations_graph = {
    "MIT": ["Chrompet Railway Station", "Chrompet Bus Stand"],
    "Chrompet Railway Station": ["MIT", "Saravana Stores Chrompet", "Chrompet Bus Stand", "GST Road Chrompet"],
    "Saravana Stores Chrompet": ["Chrompet Railway Station", "KFC Chrompet", "Hasthinapuram Main Road"],
    "Chrompet Bus Stand": ["MIT", "Chrompet Railway Station", "Hasthinapuram Main Road"],
    "Hasthinapuram Main Road": ["Chrompet Bus Stand", "Saravana Stores Chrompet", "Kumaran Kundram Temple", "Radha Nagar", "Chrompet Market"],
    "Kumaran Kundram Temple": ["Hasthinapuram Main Road", "Kumaran Nagar"],
    "Kumaran Nagar": ["Kumaran Kundram Temple", "Thiruneermalai Road", "Pammal Main Road"],
    "Pammal Main Road": ["Kumaran Nagar", "Pallavaram Bus Stand", "Thiruneermalai Road"],
    "Pallavaram Bus Stand": ["Pammal Main Road", "Pallavaram Railway Station", "Pallavaram Signal"],
    "Pallavaram Railway Station": ["Pallavaram Bus Stand", "Tirusulam Bridge"],
    "Tirusulam Bridge": ["Pallavaram Railway Station", "Chennai Airport Metro"],
    "Chennai Airport Metro": ["Tirusulam Bridge"],
    "GST Road Chrompet": ["Chrompet Railway Station", "KFC Chrompet", "Chrompet Market", "Pallavaram Signal"],
    "KFC Chrompet": ["GST Road Chrompet", "Saravana Stores Chrompet"],
    "Chrompet Market": ["GST Road Chrompet", "Hasthinapuram Main Road"],
    "Thiruneermalai Road": ["Pammal Main Road", "Kumaran Nagar"],
    "Pallavaram Signal": ["Pallavaram Bus Stand", "GST Road Chrompet"],
    "Radha Nagar": ["Hasthinapuram Main Road"],
}

# Add dummy coordinates for each location
coordinates = {
    "MIT": [12.9489, 80.1391],
    "Chrompet Railway Station": [12.9507, 80.1402],
    "Saravana Stores Chrompet": [12.9501, 80.1420],
    "Chrompet Bus Stand": [12.9492, 80.1411],
    "Hasthinapuram Main Road": [12.9480, 80.1435],
    "Kumaran Kundram Temple": [12.9472, 80.1450],
    "Kumaran Nagar": [12.9465, 80.1470],
    "Pammal Main Road": [12.9440, 80.1485],
    "Pallavaram Bus Stand": [12.9420, 80.1500],
    "Pallavaram Railway Station": [12.9415, 80.1515],
    "Tirusulam Bridge": [12.9400, 80.1530],
    "Chennai Airport Metro": [12.9385, 80.1545],
    "GST Road Chrompet": [12.9500, 80.1390],
    "KFC Chrompet": [12.9495, 80.1405],
    "Chrompet Market": [12.9478, 80.1425],
    "Thiruneermalai Road": [12.9450, 80.1460],
    "Pallavaram Signal": [12.9425, 80.1490],
    "Radha Nagar": [12.9470, 80.1440],
}
